### ISSUE TITLE
feature request: Add an optional "signature" field to the eventHandlers.

### ISSUE THREAD

**Issue by LiRiu** [hyperoracle/zkgraph#64]
The "eventHandlers" field in the current configuration file only supports two fields: "event define" and "handle function".
```yaml
      eventHandlers:
        - event: OrderFulfilled(bytes32,address,address,address,tuple[],tuple[])
          handler: handleEvents
```
If the event contains dynamic data types, it can be a bit challenging to define. 
For example, the `OrderFulfilled` event in the opensea.seaport protocol includes two dynamic struct types. These "dynamic events" are not fully expressed on etherscan and only record tuple[].
If the developer only defines the dynamic type field as `tuple[]` (as written in the above YAML), then esig will calculate incorrectly. It won't be able to filter the correct events.
### advice
Add a "signature" field to the eventHandlers in the configuration file. Use it to directly assign the value of esig.

**Comment by nom4dv3** [comment]
Good point. Yes I can see the actual event def in your code: 
`OrderFulfilled(bytes32,address,address,address,(uint8,address,uint256,uint256)[],(uint8,address,uint256,uint256,address)[])` , a bit hard to write I agree.

Maybe we can add this pattern:
```yaml
      eventHandlers:
        - signature: "0x9d9af8e38d66c62e2c12f0225249fd9d721c54b83f48d9352c97c6cacdcb6f31"
          handler: handleEvents
```
If both exists, hyperoracle node needs to validate the consistency of them, and use the signature directly if valid, discard zkgraph if not.
```yaml
      eventHandlers:
        - event: "OrderFulfilled(bytes32,address,address,address,tuple[],tuple[])"
          signature: "0x9d9af8e38d66c62e2c12f0225249fd9d721c54b83f48d9352c97c6cacdcb6f31"
          handler: handleEvents
```
